
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgcgicxtcxeubuoqusic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnY2dpY3h0Y3hldWJ1b3F1c2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODU5MzQsImV4cCI6MjA2NjU2MTkzNH0.jQRaDI9_OtPKSuC7BZWDBSbBKw5kk1HxAwICmrcpAiM";

// Ensure we have valid URLs before creating the client
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Supabase configuration missing');
  throw new Error('Supabase URL and key are required');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    redirectTo: window.location.origin,
    flowType: 'pkce'
  }
});
